name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create documentation folder
        run: |
          mkdir -p docs
          cp README.md docs/index.md
          echo "# GWAS & Multiomics Bioinformatics Workshop" > docs/_config.yml
          echo "include:" >> docs/_config.yml
          echo "  - Sessions/" >> docs/_config.yml
          echo "  - Exercises/" >> docs/_config.yml
          echo "  - Quizzes/" >> docs/_config.yml
          echo "  - Data/" >> docs/_config.yml

      - name: Copy content to docs
        run: |
          cp -r Sessions docs/
          cp -r Exercises docs/
          cp -r Quizzes docs/
          cp -r Data docs/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
